CREATE DATABASE BASKETBALLDB
USE BASKETBALLDB

DROP TABLE IF EXISTS FIXTURE;

CREATE TABLE FIXTURE(
    FIXTUREID INT NOT NULL,
    FIXTUREDATE DATETIME NOT NULL,
    FIXTUREVENUE NVARCHAR(50) NOT NULL,
    FIXTUREMEMBERNAME NVARCHAR(50),
    FIXTURECOST FLOAT,
    CONSTRAINT PK_FIXTUREID PRIMARY KEY (FIXTUREID)
)

DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER(
    MEMBERID NVARCHAR(50) NOT NULL,
    MEMBERNAME NVARCHAR(50) NOT NULL,
    MEMBERPASSWORD NVARCHAR(50) NOT NULL,
    CONSTRAINT PK_MEMBERID PRIMARY KEY (MEMBERID)
)


SELECT * FROM MEMBER
SELECT * FROM FIXTURE