CREATE DATABASE BASKETBALLDB
USE BASKETBALLDB

DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER(
    MEMBERID NVARCHAR(50) NOT NULL,
    MEMBERNAME NVARCHAR(50) NOT NULL,
    MEMBERPASSWORD NVARCHAR(50) NOT NULL,
    CONSTRAINT PK_MEMBERID PRIMARY KEY (MEMBERID)
)

DROP TABLE IF EXISTS FIXTURE;

CREATE TABLE FIXTURE(
    FIXTURENAME NVARCHAR(50) NOT NULL,
    FIXTUREDATE DATETIME NOT NULL,
    FIXTUREVENUE NVARCHAR(50) NOT NULL,
    CONSTRAINT PK_FIXTUREDATE PRIMARY KEY (FIXTUREDATE)
)

SELECT * FROM MEMBER
SELECT * FROM FIXTURE